/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
struct meta_seq_int {
   void *_b ;
   void *_e ;
}   ;
struct seq_int {
   int * __SEQ  _p ;
   struct meta_seq_int _ms ;
}   ;
typedef struct seq_int seq_int;
seq_int getSeq_q(void) ;
seq_int getSeq_q(void) 
{ struct seq_int __retres ;
  struct seq_int __cil_tmp2 ;
  seq_int __cil_tmp3 ;

  {
  __retres._ms._e = (void *)0;
  __retres._ms._b = (void *)0;
  __retres._p = (int */* __SEQ  */)0;
  __cil_tmp2._p = (int */* __SEQ  */)5;
  __cil_tmp2._ms._b = (void *)0;
  __cil_tmp2._ms._e = (void *)0;
  __retres = __cil_tmp2;
  __cil_tmp3._p = __retres._p;
  __cil_tmp3._ms._b = __retres._ms._b;
  __cil_tmp3._ms._e = __retres._ms._e;
  return (__cil_tmp3);
}
}
