/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
struct meta_seq_int {
   void *_b ;
   void *_e ;
}   ;
struct seq_int {
   int * __SEQ  _p ;
   struct meta_seq_int _ms ;
}   ;
typedef struct seq_int seq_int;
int foo(int x ) ;
int foo(int x ) 
{ seq_int p ;
  int *safe ;
  int __retres ;
  seq_int __cil_tmp5 ;

  {
  safe = (int *)0;
  p._ms._e = (void *)0;
  p._ms._b = (void *)0;
  p._p = (int */* __SEQ  */)0;
  __cil_tmp5._p = p._p + x;
  __cil_tmp5._ms._b = p._ms._b;
  __cil_tmp5._ms._e = p._ms._e;
  p = __cil_tmp5;
  CHECK_SEQ2SAFE(p._ms._b, p._ms._e, (void *)p._p, sizeof(int ), sizeof(int ), 0,
                 0);
  safe = (int *)p._p;
  CHECK_NULL((void *)safe);
  __retres = *safe;
  return (__retres);
}
}
