/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
struct meta_seq_int {
   void *_b ;
   void *_e ;
}   ;
struct seq_int {
   int * __SEQ  _p ;
   struct meta_seq_int _ms ;
}   ;
typedef struct seq_int seq_int;
seq_int sneaky_q(void) ;
seq_int sneaky_q(void) 
{ int ( __SEQ  local)[2] ;
  struct seq_int x ;
  struct seq_int __retres ;
  struct seq_int __cil_tmp5 ;
  struct seq_int __cil_tmp6 ;
  struct seq_int __cil_tmp7 ;
  seq_int __cil_tmp8 ;

  {
  __retres._ms._e = (void *)0;
  __retres._ms._b = (void *)0;
  __retres._p = (int */* __SEQ  */)0;
  x._ms._e = (void *)0;
  x._ms._b = (void *)0;
  x._p = (int */* __SEQ  */)0;
  __cil_tmp5._p = (int */* __SEQ  */)(local);
  __cil_tmp5._ms._b = local;
  __cil_tmp5._ms._e = local + 2;
  x = __cil_tmp5;
  __cil_tmp6._p = x._p + 200;
  __cil_tmp6._ms._b = x._ms._b;
  __cil_tmp6._ms._e = x._ms._e;
  x = __cil_tmp6;
  __cil_tmp7._p = x._p;
  __cil_tmp7._ms._b = x._ms._b;
  __cil_tmp7._ms._e = x._ms._e;
  __retres = __cil_tmp7;
  __cil_tmp8._p = __retres._p;
  __cil_tmp8._ms._b = __retres._ms._b;
  __cil_tmp8._ms._e = __retres._ms._e;
  return (__cil_tmp8);
}
}
int main(void) ;
int main(void) 
{ struct seq_int plocal ;
  struct seq_int tmp ;
  int __retres ;
  seq_int __cil_tmp4 ;
  struct seq_int __cil_tmp5 ;
  struct seq_int __cil_tmp6 ;

  {
  tmp._ms._e = (void *)0;
  tmp._ms._b = (void *)0;
  tmp._p = (int */* __SEQ  */)0;
  plocal._ms._e = (void *)0;
  plocal._ms._b = (void *)0;
  plocal._p = (int */* __SEQ  */)0;
  __ccuredAlwaysStopOnError = 0;
  __ccuredUseStrings = 1;
  __ccuredLogNonPointers = 0;
  __ccuredInit();
  __cil_tmp4 = sneaky_q();
  __cil_tmp5._p = __cil_tmp4._p;
  __cil_tmp5._ms._b = __cil_tmp4._ms._b;
  __cil_tmp5._ms._e = __cil_tmp4._ms._e;
  tmp = __cil_tmp5;
  __cil_tmp6._p = tmp._p;
  __cil_tmp6._ms._b = tmp._ms._b;
  __cil_tmp6._ms._e = tmp._ms._e;
  plocal = __cil_tmp6;
  CHECK_SEQ2SAFE(plocal._ms._b, plocal._ms._e, (void *)(plocal._p - 200), sizeof(int ),
                 sizeof(int ), 1, 0);
  __retres = *(plocal._p - 200);
  return (__retres);
}
}
