/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#define CCURED_SPLIT_ARGUMENTS
// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
char ( __FSEQ  buffer)[17]  ;
struct meta_fseqp_long {
   void *_e ;
}   ;
int main(void) ;
int main(void) 
{ long * __FSEQ  p ;
  int __retres ;
  long * __FSEQ  __cil_tmp3 ;
  void *p_e6 ;
  void *__cil_tmp3_e7 ;

  {
  p_e6 = (void *)0;
  p = (long */* __FSEQ  */)0;
  __ccuredAlwaysStopOnError = 0;
  __ccuredUseStrings = 1;
  __ccuredLogNonPointers = 0;
  __ccuredInit();
  CHECK_FSEQALIGN(sizeof(long ), (void *)((long */* __FSEQ  */)(buffer)), buffer + 17);
  __cil_tmp3 = (long */* __FSEQ  */)(buffer);
  __cil_tmp3_e7 = buffer + 17;
  p_e6 = __cil_tmp3_e7;
  p = __cil_tmp3;
  CHECK_FSEQARITH2SAFE((void *)p, p_e6, (void *)(p + 2), sizeof(long ), sizeof(long ),
                       1, 0, 0);
  __retres = (int )*(p + 2);
  return (__retres);
}
}
