/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#define CCURED_SPLIT_ARGUMENTS
// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
char ( __FSEQ  buffer)[17]  ;
struct meta_fseqp_void {
   void *_e ;
}   ;
struct fseqp_void {
   void * __FSEQ  _p ;
   struct meta_fseqp_void _ms ;
}   ;
extern struct fseqp_void /*1*/__align_seq_ff(void * __FSEQ  p_p , void *p_ms_e , unsigned int size ) ;
struct meta_fseqp_long {
   void *_e ;
}   ;
int main(void) ;
int main(void) 
{ long * __FSEQ  p ;
  long * __FSEQ  tmp ;
  int __retres ;
  void * __FSEQ  __cil_tmp4 ;
  struct fseqp_void __cil_tmp5 ;
  long * __FSEQ  __cil_tmp6 ;
  long * __FSEQ  __cil_tmp7 ;
  void *p_e13 ;
  void *tmp_e14 ;
  void *__cil_tmp4_e15 ;
  void *__cil_tmp6_e16 ;
  void *__cil_tmp7_e17 ;

  {
  tmp_e14 = (void *)0;
  tmp = (long */* __FSEQ  */)0;
  p_e13 = (void *)0;
  p = (long */* __FSEQ  */)0;
  __ccuredAlwaysStopOnError = 0;
  __ccuredUseStrings = 1;
  __ccuredLogNonPointers = 0;
  __ccuredInit();
  __cil_tmp4 = (void */* __FSEQ  */)(buffer);
  __cil_tmp4_e15 = buffer + 17;
  __cil_tmp5 = /*1*/__align_seq_ff(__cil_tmp4, __cil_tmp4_e15, sizeof(*p));
  CHECK_FSEQALIGN(sizeof(long ), (void *)((long */* __FSEQ  */)__cil_tmp5._p), __cil_tmp5._ms._e);
  __cil_tmp6 = (long */* __FSEQ  */)__cil_tmp5._p;
  __cil_tmp6_e16 = __cil_tmp5._ms._e;
  tmp_e14 = __cil_tmp6_e16;
  tmp = __cil_tmp6;
  __cil_tmp7 = tmp;
  __cil_tmp7_e17 = tmp_e14;
  p_e13 = __cil_tmp7_e17;
  p = __cil_tmp7;
  CHECK_FSEQARITH2SAFE((void *)p, p_e13, (void *)(p + 2), sizeof(long ), sizeof(long ),
                       1, 0, 0);
  __retres = (int )*(p + 2);
  return (__retres);
}
}
