/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
double (( __FSEQ  a)[8])[8]  ;
struct meta_fseqp_double {
   void *_e ;
}   ;
struct fseqp_double {
   double * __FSEQ  _p ;
   struct meta_fseqp_double _ms ;
}   ;
typedef struct fseqp_double fseqp_double;
int zero(void) ;
int zero(void) 
{ fseqp_double pa ;
  int i ;
  double *tmp ;
  int __retres ;
  fseqp_double __cil_tmp5 ;
  fseqp_double __cil_tmp6 ;

  {
  tmp = (double *)0;
  pa._ms._e = (void *)0;
  pa._p = (double */* __FSEQ  */)0;
  __cil_tmp5._p = (double */* __FSEQ  */)(a);
  __cil_tmp5._ms._e = a + 8;
  pa = __cil_tmp5;
  i = 0;
  while ((unsigned int )i < sizeof(a) / sizeof(double )) {
    CHECK_FSEQ2SAFE(pa._ms._e, (void *)pa._p, sizeof(double ), sizeof(double ), 0,
                    0);
    tmp = (double *)pa._p;
    CHECK_FSEQARITH((void *)pa._p, sizeof(double ), (void *)(pa._p + 1), pa._ms._e,
                    0);
    __cil_tmp6._p = pa._p + 1;
    __cil_tmp6._ms._e = pa._ms._e;
    pa = __cil_tmp6;
    CHECK_NULL((void *)tmp);
    *tmp = 0.0;
    i ++;
  }
  __retres = 0;
  return (__retres);
}
}
