/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
struct meta_fseqp_int {
   void *_e ;
}   ;
struct fseqp_int {
   int * __FSEQ  _p ;
   struct meta_fseqp_int _ms ;
}   ;
typedef struct fseqp_int fseqp_int;
int addAll_f(fseqp_int p , int len ) ;
int addAll_f(fseqp_int p , int len ) 
{ int sum ;
  int i ;
  int __retres ;

  {
  sum = 0;
  i = 0;
  while (i < len) {
    CHECK_FSEQARITH2SAFE((void *)p._p, p._ms._e, (void *)(p._p + i), sizeof(int ),
                         sizeof(int ), 1, 0, 0);
    sum += *(p._p + i);
    i ++;
  }
  __retres = sum;
  return (__retres);
}
}
