/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
struct _sized_a_p_int {
   unsigned int _size ;
   int *( __SIZED  _array)[0]  __attribute__((__packed__)) ;
};
typedef struct _sized_a_p_int _sized_a_p_int;
struct open {
   int count ;
   _sized_a_p_int __SIZED   rest ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
extern void *malloc(unsigned int  ) ;
int main(void) ;
int main(void) 
{ struct open *p ;
  struct open *tmp ;
  int __retres ;
  void *__cil_tmp4 ;
  void *__cil_tmp5 ;

  {
  tmp = (struct open *)0;
  p = (struct open *)0;
  __ccuredAlwaysStopOnError = 0;
  __ccuredUseStrings = 1;
  __ccuredLogNonPointers = 0;
  __ccuredInit();
  __cil_tmp4 = malloc(20U);
  tmp = (struct open *)__cil_tmp4;
  p = (struct open *)tmp;
  CHECK_NULL((void *)p);
  __cil_tmp5 = CHECK_FETCH_INDEX_END((void *)(& p->rest._array[5]), (void *)(p->rest._array),
                                     0);
  CHECK_SEQ2SAFE((void *)(p->rest._array), __cil_tmp5, (void *)(& p->rest._array[5]),
                 sizeof(int *), sizeof(int *), 1, 1);
  __retres = (int )p->rest._array[5];
  return (__retres);
}
}
