/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
struct _sized_a_int {
   unsigned int _size ;
   int ( __SIZED  _array)[0]  __attribute__((__packed__)) ;
};
typedef struct _sized_a_int _sized_a_int;
extern _sized_a_int __SIZED   a_l ;
int main(void) ;
int main(void) 
{ int __retres ;
  void *__cil_tmp2 ;

  {
  __ccuredAlwaysStopOnError = 0;
  __ccuredUseStrings = 1;
  __ccuredLogNonPointers = 0;
  __ccuredInit();
  __cil_tmp2 = CHECK_FETCH_INDEX_END((void *)(& a_l._array[3]), (void *)(a_l._array),
                                     0);
  CHECK_SEQ2SAFE((void *)(a_l._array), __cil_tmp2, (void *)(& a_l._array[3]), sizeof(int ),
                 sizeof(int ), 1, 1);
  __retres = a_l._array[3];
  return (__retres);
}
}
