/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
struct _sized_a_p_int {
   unsigned int _size ;
   int *( __SIZED  _array)[8]  __attribute__((__packed__)) ;
};
typedef struct _sized_a_p_int _sized_a_p_int;
_sized_a_p_int __SIZED   a_ls  __INDEX   ;
void __globinit_ex25(void) 
{ unsigned int iter1 ;

  {
  a_ls._size = (8U * sizeof(int *) + 3U) >> 2;
  return;
}
}
