/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
struct meta_wildp_int {
   void *_b ;
}   ;
struct wildp_int {
   int * __WILD  _p ;
   struct meta_wildp_int _ms ;
}   ;
typedef struct wildp_int wildp_int;
struct meta_wildp_p_int {
   void *_b ;
}   ;
struct wildp_s_wildp_int {
   struct wildp_int * __WILD  _p ;
   struct meta_wildp_p_int _ms ;
}   ;
typedef struct wildp_s_wildp_int wildp_s_wildp_int;
int foo_w(wildp_int a ) ;
int foo_w(wildp_int a ) 
{ wildp_s_wildp_int g ;
  int __retres ;
  wildp_s_wildp_int __cil_tmp4 ;

  {
  g._ms._b = (void *)0;
  __cil_tmp4._p = (struct wildp_int */* __WILD  */)a._p;
  __cil_tmp4._ms._b = a._ms._b;
  g = __cil_tmp4;
  __retres = 0;
  return (__retres);
}
}
