/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#define CCURED_SPLIT_ARGUMENTS
// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
struct meta_wildp_int {
   void *_b ;
}   ;
struct wildp_int {
   int * __WILD  _p ;
   struct meta_wildp_int _ms ;
}   ;
typedef struct wildp_int wildp_int;
struct __anonstruct_x2_1 {
   wildp_int a1 ;
   int a2 ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
struct _tagged_int {
   unsigned int _len ;
   int _data  __attribute__((__packed__)) ;
   int _tags[(sizeof(int ) + 127U) >> 7]  __attribute__((__packed__)) ;
};
typedef struct _tagged_int _tagged_int;
_tagged_int y1_t  __TAGGED   =    {(sizeof(int ) + 3U) >> 2};
struct meta_wildp_p_int {
   void *_b ;
}   ;
struct wildp_s_wildp_int {
   struct wildp_int * __WILD  _p ;
   struct meta_wildp_p_int _ms ;
}   ;
typedef struct wildp_s_wildp_int wildp_s_wildp_int;
wildp_s_wildp_int x1_w  =    {(struct wildp_int */* __WILD  */)(& y1_t._data), {& y1_t._data}};
_tagged_int y2_t  __TAGGED   =    {(sizeof(int ) + 3U) >> 2};
struct meta_wildp_s___anonstruct_x2_1 {
   void *_b ;
}   ;
struct wildp_s___anonstruct_x2_1 {
   struct __anonstruct_x2_1 * __WILD  _p ;
   struct meta_wildp_s___anonstruct_x2_1 _ms ;
}   ;
typedef struct wildp_s___anonstruct_x2_1 wildp_s___anonstruct_x2_1;
wildp_s___anonstruct_x2_1 x2_w  =    {(struct __anonstruct_x2_1 */* __WILD  */)(& y2_t._data), {& y2_t._data}};
