/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#define CCURED_SPLIT_ARGUMENTS
// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
void */*1*/identity(void *x ) ;
int main(void) ;
int main(void) 
{ int *p ;
  int **res_pp ;
  int **tmp ;
  int *res_p ;
  int *tmp___0 ;
  int __retres ;
  void *__cil_tmp7 ;
  void *__cil_tmp8 ;

  {
  tmp___0 = (int *)0;
  res_p = (int *)0;
  tmp = (int **)0;
  res_pp = (int **)0;
  p = (int *)0;
  __ccuredAlwaysStopOnError = 0;
  __ccuredUseStrings = 1;
  __ccuredLogNonPointers = 0;
  __ccuredInit();
  p = (int *)0;
  __cil_tmp7 = /*1*/identity((void *)((void *)(& p)));
  tmp = (int **)__cil_tmp7;
  res_pp = (int **)tmp;
  __cil_tmp8 = /*1*/identity((void *)((void *)p));
  tmp___0 = (int *)__cil_tmp8;
  res_p = (int *)tmp___0;
  __retres = 0;
  return (__retres);
}
}
void */*1*/identity(void *x ) ;
void */*1*/identity(void *x ) 
{ void *__retres ;

  {
  __retres = (void *)0;
  __retres = (void *)x;
  return (__retres);
}
}
