/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#define CCURED_SPLIT_ARGUMENTS
// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
struct __anonstruct_f3_2 {
   int *a1 ;
   int *a2 ;
   int *a3 ;
};
union __anonunion_x_1 {
   int *f1 ;
   int *(f2)[2] ;
   struct __anonstruct_f3_2 f3 ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
union __anonunion_x_1 *x  ;
int *foo(void) ;
int *foo(void) 
{ int *__retres ;

  {
  __retres = (int *)0;
  CHECK_NULL((void *)x);
  __retres = (int *)x->f1;
  return (__retres);
}
}
