/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#define CCURED_SPLIT_ARGUMENTS
// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
int foo(int *p ) ;
int foo(int *p ) 
{ int *q ;
  int *tmp ;
  int __retres ;
  void *__cil_tmp5 ;

  {
  tmp = (int *)0;
  q = (int *)0;
  __cil_tmp5 = (unsigned int )((void *)((unsigned long )p + (unsigned long )(4U * sizeof(*p))));
  tmp = (int *)__cil_tmp5;
  q = (int *)tmp;
  CHECK_NULL((void *)q);
  __retres = *q;
  return (__retres);
}
}
