/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#define CCURED_SPLIT_ARGUMENTS
// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
int ( __FSEQ  g)[8]  ;
struct meta_seq_void {
   void *_b ;
   void *_e ;
}   ;
struct meta_seq_int {
   void *_b ;
   void *_e ;
}   ;
int main(void) ;
int main(void) 
{ int *pg ;
  int * __SEQ  sg ;
  int * __SEQ  tmp ;
  int __retres ;
  void * __SEQ  __cil_tmp5 ;
  void * __SEQ  __cil_tmp6 ;
  void * __SEQ  __cil_tmp7 ;
  int * __SEQ  __cil_tmp8 ;
  int * __SEQ  __cil_tmp9 ;
  void *sg_b17 ;
  void *sg_e18 ;
  void *tmp_b19 ;
  void *tmp_e20 ;
  void *__cil_tmp5_b21 ;
  void *__cil_tmp5_e22 ;
  void *__cil_tmp6_b23 ;
  void *__cil_tmp6_e24 ;
  void *__cil_tmp7_b25 ;
  void *__cil_tmp7_e26 ;
  void *__cil_tmp8_b27 ;
  void *__cil_tmp8_e28 ;
  void *__cil_tmp9_b29 ;
  void *__cil_tmp9_e30 ;

  {
  tmp_e20 = (void *)0;
  tmp_b19 = (void *)0;
  tmp = (int */* __SEQ  */)0;
  sg_e18 = (void *)0;
  sg_b17 = (void *)0;
  sg = (int */* __SEQ  */)0;
  pg = (int *)0;
  __ccuredAlwaysStopOnError = 0;
  __ccuredUseStrings = 1;
  __ccuredLogNonPointers = 0;
  __ccuredInit();
  pg = (int *)((int *)(& g[2]));
  if ((void *)((void *)pg)) {
    __cil_tmp6 = (void *)((void *)pg);
    __cil_tmp6_b23 = (void *)((void *)pg);
    __cil_tmp6_e24 = (void *)((void *)pg) + 2U * sizeof(int );
    __cil_tmp5_e22 = __cil_tmp6_e24;
    __cil_tmp5_b21 = __cil_tmp6_b23;
    __cil_tmp5 = __cil_tmp6;
  } else {
    __cil_tmp7 = 0;
    __cil_tmp7_b25 = (void *)0;
    __cil_tmp7_e26 = (void *)0;
    __cil_tmp5_e22 = __cil_tmp7_e26;
    __cil_tmp5_b21 = __cil_tmp7_b25;
    __cil_tmp5 = __cil_tmp7;
  }
  CHECK_SEQALIGN(sizeof(int ), (void *)((int */* __SEQ  */)__cil_tmp5), __cil_tmp5_b21,
                 __cil_tmp5_e22);
  __cil_tmp8 = (int */* __SEQ  */)__cil_tmp5;
  __cil_tmp8_b27 = __cil_tmp5_b21;
  __cil_tmp8_e28 = __cil_tmp5_e22;
  tmp_e20 = __cil_tmp8_e28;
  tmp_b19 = __cil_tmp8_b27;
  tmp = __cil_tmp8;
  __cil_tmp9 = tmp;
  __cil_tmp9_b29 = tmp_b19;
  __cil_tmp9_e30 = tmp_e20;
  sg_e18 = __cil_tmp9_e30;
  sg_b17 = __cil_tmp9_b29;
  sg = __cil_tmp9;
  CHECK_SEQ2SAFE(sg_b17, sg_e18, (void *)(sg + 1), sizeof(int ), sizeof(int ), 1,
                 0);
  __retres = *(sg + 1);
  return (__retres);
}
}
