/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#define CCURED_SPLIT_ARGUMENTS
// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
struct msghdr;
struct iovec;
struct meta_fseqp_s_iovec {
   void *_e ;
}   ;
struct fseqp_s_iovec {
   struct iovec * __FSEQ  _p ;
   struct meta_fseqp_s_iovec _ms ;
}   ;
typedef struct fseqp_s_iovec fseqp_s_iovec;
struct msghdr {
   void *msg_name ;
   int msg_namelen ;
   fseqp_s_iovec msg_iov ;
   int msg_iovlen ;
   void *msg_control ;
   int msg_controllen ;
   int msg_flags ;
};
struct iovec {
   char *iov_base ;
   int iov_len ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
struct msghdr_COMPAT;
struct iovec_COMPAT;
struct msghdr_COMPAT {
   void *msg_name ;
   int msg_namelen ;
   struct iovec_COMPAT *msg_iov ;
   int msg_iovlen ;
   void *msg_control ;
   int msg_controllen ;
   int msg_flags ;
};
extern int sendmsg(int fd , struct msghdr_COMPAT *msg , int flags ) ;
__inline static int /*1*/sendmsg_wrapper3(int fd , struct msghdr *msg , int flags ) ;
int foo_f(int fd , struct iovec * __FSEQ  array , void *array_e , int array_len ) ;
int foo_f(int fd , struct iovec * __FSEQ  array , void *array_e , int array_len ) 
{ struct msghdr msg ;
  struct iovec *foo___0 ;
  int tmp ;
  int __retres ;
  struct iovec * __FSEQ  __cil_tmp8 ;
  int __cil_tmp9 ;
  void *__cil_tmp8_e13 ;

  {
  foo___0 = (struct iovec *)0;
  msg.msg_control = (void *)0;
  msg.msg_iov._ms._e = (void *)0;
  msg.msg_iov._p = (struct iovec */* __FSEQ  */)0;
  msg.msg_name = (void *)0;
  msg.msg_name = (void *)0;
  msg.msg_namelen = 0;
  __cil_tmp8 = array;
  __cil_tmp8_e13 = array_e;
  msg.msg_iov._ms._e = __cil_tmp8_e13;
  msg.msg_iov._p = __cil_tmp8;
  msg.msg_iovlen = array_len;
  msg.msg_control = (void *)0;
  msg.msg_controllen = 0;
  msg.msg_flags = 0;
  CHECK_FSEQARITH((void *)msg.msg_iov._p, sizeof(struct iovec ), (void *)(msg.msg_iov._p + 1),
                  msg.msg_iov._ms._e, 0);
  CHECK_FSEQ2SAFE(msg.msg_iov._ms._e, (void *)(msg.msg_iov._p + 1), sizeof(struct iovec ),
                  sizeof(struct iovec ), 0, 0);
  foo___0 = (struct iovec *)(msg.msg_iov._p + 1);
  __cil_tmp9 = /*1*/sendmsg_wrapper3(fd, (struct msghdr *)(& msg), 0);
  tmp = __cil_tmp9;
  __retres = tmp;
  return (__retres);
}
}
struct iovec_COMPAT {
   char *iov_base ;
   int iov_len ;
};
extern void __deepcopy_msghdr_to_compat_sscsfs_(struct msghdr_COMPAT *compat , struct msghdr *fat ) ;
static char __string1[45]  = 
  {      'A',      'b',      'o',      'r', 
        't',      ' ',      'd',      'e', 
        'e',      'p',      'c',      'o', 
        'p',      'y',      '_',      't', 
        'o',      '_',      'c',      'o', 
        'm',      'p',      'a',      't', 
        ' ',      'f',      'o',      'r', 
        ' ',      'm',      's',      'g', 
        'h',      'd',      'r',      '.', 
        'm',      's',      'g',      '_', 
        'n',      'a',      'm',      'e', 
        '\000'};
static char __string2[44]  = 
  {      'A',      'b',      'o',      'r', 
        't',      ' ',      'd',      'e', 
        'e',      'p',      'c',      'o', 
        'p',      'y',      '_',      't', 
        'o',      '_',      'c',      'o', 
        'm',      'p',      'a',      't', 
        ' ',      'f',      'o',      'r', 
        ' ',      'm',      's',      'g', 
        'h',      'd',      'r',      '.', 
        'm',      's',      'g',      '_', 
        'i',      'o',      'v',      '\000'};
static char __string3[48]  = 
  {      'A',      'b',      'o',      'r', 
        't',      ' ',      'd',      'e', 
        'e',      'p',      'c',      'o', 
        'p',      'y',      '_',      't', 
        'o',      '_',      'c',      'o', 
        'm',      'p',      'a',      't', 
        ' ',      'f',      'o',      'r', 
        ' ',      'm',      's',      'g', 
        'h',      'd',      'r',      '.', 
        'm',      's',      'g',      '_', 
        'c',      'o',      'n',      't', 
        'r',      'o',      'l',      '\000'};
extern void __deepcopy_msghdr_to_compat_sscsfs_(struct msghdr_COMPAT *compat , struct msghdr *fat ) ;
extern void __deepcopy_msghdr_to_compat_sscsfs_(struct msghdr_COMPAT *compat , struct msghdr *fat ) 
{ void *__cil_tmp3 ;
  int dest_mangling4 ;
  struct iovec *__cil_tmp5 ;
  int dest_mangling6 ;
  void *__cil_tmp7 ;
  int dest_mangling8 ;
  void *__cil_tmp9 ;
  void *__cil_tmp10 ;
  void *__cil_tmp11 ;
  void *__cil_tmp12 ;
  void *__cil_tmp13 ;
  void *__cil_tmp14 ;

  {
  __cil_tmp7 = (void *)0;
  __cil_tmp5 = (struct iovec *)0;
  __cil_tmp3 = (void *)0;
  CHECK_NULL((void *)fat);
  __cil_tmp9 = (void *)fat->msg_name;
  __cil_tmp7 = (void *)__cil_tmp9;
  if ((int )(! __cil_tmp7)) {
    {
    CHECK_NULL((void *)compat);
    compat->msg_name = (void *)0;
    }
  } else {
    {
    dest_mangling8 = 1;
    if (dest_mangling8) {
      {
      __cil_tmp10 = (void *)__cil_tmp7;
      CHECK_NULL((void *)compat);
      compat->msg_name = (void *)__cil_tmp10;
      }
    } else {
      {
      abort_deepcopy((char *)(& __string1[0]));
      }
    }
    }
  }
  CHECK_NULL((void *)compat);
  CHECK_NULL((void *)fat);
  compat->msg_namelen = fat->msg_namelen;
  __cil_tmp11 = (void */* __FSEQ  */)fat->msg_iov._p;
  __cil_tmp5 = (struct iovec *)__cil_tmp11;
  if ((int )(! __cil_tmp5)) {
    {
    CHECK_NULL((void *)compat);
    compat->msg_iov = (struct iovec_COMPAT *)0;
    }
  } else {
    {
    dest_mangling6 = 1;
    if (dest_mangling6) {
      {
      __cil_tmp12 = (void *)__cil_tmp5;
      CHECK_NULL((void *)compat);
      compat->msg_iov = (struct iovec_COMPAT *)__cil_tmp12;
      }
    } else {
      {
      abort_deepcopy((char *)(& __string2[0]));
      }
    }
    }
  }
  CHECK_NULL((void *)compat);
  CHECK_NULL((void *)fat);
  compat->msg_iovlen = fat->msg_iovlen;
  __cil_tmp13 = (void *)fat->msg_control;
  __cil_tmp3 = (void *)__cil_tmp13;
  if ((int )(! __cil_tmp3)) {
    {
    CHECK_NULL((void *)compat);
    compat->msg_control = (void *)0;
    }
  } else {
    {
    dest_mangling4 = 1;
    if (dest_mangling4) {
      {
      __cil_tmp14 = (void *)__cil_tmp3;
      CHECK_NULL((void *)compat);
      compat->msg_control = (void *)__cil_tmp14;
      }
    } else {
      {
      abort_deepcopy((char *)(& __string3[0]));
      }
    }
    }
  }
  CHECK_NULL((void *)compat);
  CHECK_NULL((void *)fat);
  compat->msg_controllen = fat->msg_controllen;
  compat->msg_flags = fat->msg_flags;
  return;
}
}
__inline static int /*1*/sendmsg_wrapper3(int fd , struct msghdr *msg , int flags ) ;
__inline static int /*1*/sendmsg_wrapper3(int fd , struct msghdr *msg , int flags ) 
{ struct msghdr_COMPAT msg1__area ;
  struct msghdr *msg1__ptrof ;
  struct msghdr *tmp ;
  struct msghdr_COMPAT *msg1 ;
  struct msghdr_COMPAT *tmp___2 ;
  int tmp___4 ;
  int tmp___5 ;
  int __retres ;
  void *__cil_tmp15 ;
  void *__cil_tmp16 ;
  void *__cil_tmp17 ;
  int __cil_tmp18 ;

  {
  tmp___2 = (struct msghdr_COMPAT *)0;
  msg1 = (struct msghdr_COMPAT *)0;
  tmp = (struct msghdr *)0;
  msg1__ptrof = (struct msghdr *)0;
  msg1__area.msg_control = (void *)0;
  msg1__area.msg_iov = (struct iovec_COMPAT *)0;
  msg1__area.msg_name = (void *)0;
  __cil_tmp15 = (void *)((void *)msg);
  tmp = (struct msghdr *)__cil_tmp15;
  msg1__ptrof = (struct msghdr *)tmp;
  if ((int )msg1__ptrof) {
    tmp___4 = 0;
    if (tmp___4) {
      __cil_tmp17 = (void *)((void *)msg1__ptrof);
      tmp___2 = (struct msghdr_COMPAT *)__cil_tmp17;
    } else {
      __deepcopy_msghdr_to_compat_sscsfs_((struct msghdr_COMPAT *)(& msg1__area),
                                          (struct msghdr *)msg1__ptrof);
      tmp___2 = (struct msghdr_COMPAT *)(& msg1__area);
    }
  } else {
    __cil_tmp16 = (void *)((void *)msg1__ptrof);
    tmp___2 = (struct msghdr_COMPAT *)__cil_tmp16;
  }
  msg1 = (struct msghdr_COMPAT *)tmp___2;
  __cil_tmp18 = sendmsg(fd, (struct msghdr_COMPAT *)msg1, flags);
  tmp___5 = __cil_tmp18;
  __retres = tmp___5;
  return (__retres);
}
}
