/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#define CCURED_SPLIT_ARGUMENTS
// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
struct meta_fseqp_int {
   void *_e ;
}   ;
struct fseqp_int {
   int * __FSEQ  _p ;
   struct meta_fseqp_int _ms ;
}   ;
typedef struct fseqp_int fseqp_int;
fseqp_int alignit_fs(int *x ) ;
fseqp_int alignit_fs(int *x ) 
{ int * __FSEQ  __retres ;
  int * __FSEQ  __cil_tmp3 ;
  fseqp_int __cil_tmp4 ;
  void *__retres_e7 ;
  void *__cil_tmp3_e8 ;

  {
  __retres_e7 = (void *)0;
  __retres = (int */* __FSEQ  */)0;
  __cil_tmp3 = (int */* __FSEQ  */)((int )x & -16);
  __cil_tmp3_e8 = (void *)0;
  __retres_e7 = __cil_tmp3_e8;
  __retres = __cil_tmp3;
  __cil_tmp4._p = __retres;
  __cil_tmp4._ms._e = __retres_e7;
  return (__cil_tmp4);
}
}
