/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#define CCURED_SPLIT_ARGUMENTS
// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
int *alignit_sq(int * __SEQ  x , void *x_b , void *x_e ) ;
int *alignit_sq(int * __SEQ  x , void *x_b , void *x_e ) 
{ int ix ;
  int *__retres ;

  {
  __retres = (int *)0;
  ix = (int )x & -16;
  CHECK_SEQ2SAFE(x_b, x_e, (void *)(x + ((ix - (int )x) >> 2)), sizeof(int ), sizeof(int ),
                 0, 0);
  __retres = (int *)(x + ((ix - (int )x) >> 2));
  return (__retres);
}
}
