/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#define CCURED_SPLIT_ARGUMENTS
// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
struct icmp {
   int various ;
   char ( __FSEQ  data)[1] ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
char ( __FSEQ  outpack)[65536]  ;
char foo(void) ;
char foo(void) 
{ char __retres ;

  {
  CHECK_NULL((void *)((struct icmp *)(outpack)));
  CHECK_SEQ2SAFE((void *)(((struct icmp *)(outpack))->data), (void *)(((struct icmp *)(outpack))->data + 1),
                 (void *)(& ((struct icmp *)(outpack))->data[8]), sizeof(char ), sizeof(char ),
                 1, 0);
  __retres = ((struct icmp *)(outpack))->data[8];
  return (__retres);
}
}
