/* Generated by CIL v. 1.3.5 */
/* print_CIL_Input is false */

#define CCURED_SPLIT_ARGUMENTS
// #define CCURED_ALLOW_PARTIAL_ELEMENTS_IN_SEQUENCE
// #define CCURED_LOG_NON_POINTERS
#define CCURED_USE_STRINGS
// #define CCURED_FAIL_IS_TERSE
// #define CCURED_ALWAYS_STOP_ON_ERROR
// Include the definition of the checkers
#define CCURED
#define CCURED_POST
#include "ccuredcheck.h"
struct printf_arguments {
   int i ;
   double d ;
   char * __ROSTRING  s ;
   long long ll ;
};
extern void __ccuredInit(void) ;
extern  __attribute__((__noreturn__)) void abort_deepcopy(char *errmsg ) ;
int *foo(int *in ) ;
int *foo(int *in ) 
{ int *__retres ;

  {
  __retres = (int *)0;
  CHECK_NULL((void *)in);
  *in = 5;
  __retres = (int *)in;
  return (__retres);
}
}
int *bar(void) ;
int *bar(void) 
{ int local ;
  int *tmp ;
  int *__retres ;
  int *__cil_tmp4 ;

  {
  __retres = (int *)0;
  tmp = (int *)0;
  local = 0;
  __cil_tmp4 = foo((int *)(& local));
  tmp = (int *)__cil_tmp4;
  __retres = (int *)tmp;
  return (__retres);
}
}
